<?php
namespace gamboamartin\notificaciones\models;

use base\orm\_modelo_parent_sin_codigo;

use gamboamartin\errores\errores;
use PDO;
use stdClass;

class not_mensaje extends _modelo_parent_sin_codigo {
    public function __construct(PDO $link){
        $tabla = 'not_mensaje';
        $columnas = array($tabla=>false,'not_emisor'=>$tabla);
        $campos_obligatorios = array('asunto','mensaje', 'not_emisor_id');

        $no_duplicados = array();

        $campos_view = array();
        $columnas_extra = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, columnas_extra: $columnas_extra,
            no_duplicados: $no_duplicados, tipo_campos: array());

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Mensajes';
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        $not_emisor = (new not_emisor(link: $this->link))->registro(registro_id: $this->registro['not_emisor_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener emisor',data: $not_emisor);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $not_emisor['not_emisor_email'].' '.$this->registro['asunto'].' '.date('YmdHis');
            $this->registro['descripcion'] = $descripcion;
        }
        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta mensaje',data: $r_alta_bd);
        }
        return $r_alta_bd;
    }


}