<?php
namespace gamboamartin\notificaciones\models;

use base\orm\_modelo_parent_sin_codigo;

use gamboamartin\errores\errores;
use PDO;
use stdClass;

class not_receptor extends _modelo_parent_sin_codigo {
    public function __construct(PDO $link){
        $tabla = 'not_receptor';
        $columnas = array($tabla=>false);
        $campos_obligatorios = array('email');

        $no_duplicados = array();

        $campos_view = array();
        $columnas_extra = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, columnas_extra: $columnas_extra,
            no_duplicados: $no_duplicados, tipo_campos: array());

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Receptores';
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['email'];
            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd($keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta emisor',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }


}