<?php
namespace gamboamartin\notificaciones\models;

use base\orm\_modelo_parent_sin_codigo;

use gamboamartin\errores\errores;
use PDO;
use stdClass;

class not_mensaje extends _modelo_parent_sin_codigo {
    public function __construct(PDO $link){
        $tabla = 'not_mensaje';
        $columnas = array($tabla=>false,'not_emisor'=>$tabla);
        $campos_obligatorios = array('asunto','mensaje', 'not_emisor_id');

        $no_duplicados = array();

        $campos_view = array();
        $columnas_extra = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, columnas_extra: $columnas_extra,
            no_duplicados: $no_duplicados, tipo_campos: array());

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Mensajes';
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        $not_emisor = (new not_emisor(link: $this->link))->registro(registro_id: $this->registro['not_emisor_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener emisor',data: $not_emisor);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $not_emisor['not_emisor_email'].' '.$this->registro['asunto'].' '.date('YmdHis');
            $this->registro['descripcion'] = $descripcion;
        }
        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta mensaje',data: $r_alta_bd);
        }
        return $r_alta_bd;
    }

    final public function envia_mensaje(int $not_mensaje_id){
        $not_mensaje = $this->registro(registro_id: $not_mensaje_id, retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener mensaje',data:  $not_mensaje);
        }

        $filtro['not_mensaje.id'] = $not_mensaje_id;
        $r_not_rel_mensaje =  (new not_rel_mensaje(link: $this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener mensajes',data:  $r_not_rel_mensaje);
        }

        $envios = array();
        $not_rel_mensajes = $r_not_rel_mensaje->registros;
        foreach ($not_rel_mensajes as $not_rel_mensaje){
            /**
             * REFACTORIZAR CON ATTR EN DATABASE
             */
            if($not_rel_mensaje['not_rel_mensaje_etapa'] === 'ALTA'){
                $mail = (new not_rel_mensaje(link: $this->link))->envia_mensaje($not_rel_mensaje['not_rel_mensaje_id']);
                if(errores::$error){
                    return $this->error->error(mensaje: 'Error al enviar mensaje',data:  $mail);
                }
                $envios[] = $mail;
            }
        }


        return $envios;
    }


}